'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Button, Card, EmptyState, PageHeader } from '@/components/backend';

interface ContentFile {
  id: string;
  title: string;
  file_path: string;
  content_type: string;
  orb_associations: number[];
  tags: string[];
  word_count: number | null;
  created_at: string;
}

interface OrbResonanceSuggestion {
  contentFile: ContentFile;
  resonanceScore: number;
  orbAlignment: string[];
  reasoning: string;
}

export default function AddSourcesPage() {
  const params = useParams();
  const router = useRouter();
  const bookId = params.id as string;
  const chapterId = params.chapterId as string;

  const [suggestions, setSuggestions] = useState<OrbResonanceSuggestion[]>([]);
  const [selectedFiles, setSelectedFiles] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [adding, setAdding] = useState(false);
  const [chapterTitle, setChapterTitle] = useState('');

  useEffect(() => {
    loadOrbResonanceSuggestions();
  }, []);

  async function loadOrbResonanceSuggestions() {
    try {
      setLoading(true);
      const response = await fetch('/api/ai/orb-resonance-suggestions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ chapterId, bookId }),
      });
      
      const data = await response.json();
      
      if (response.ok) {
        setSuggestions(data.suggestions || []);
        setChapterTitle(data.chapterTitle || 'Chapter');
      } else {
        console.error('Error loading suggestions:', data.error);
      }
    } catch (err) {
      console.error('Error loading Orb resonance suggestions:', err);
    } finally {
      setLoading(false);
    }
  }

  function toggleFileSelection(fileId: string) {
    setSelectedFiles(prev => 
      prev.includes(fileId) 
        ? prev.filter(id => id !== fileId)
        : [...prev, fileId]
    );
  }

  async function handleAddSources() {
    if (selectedFiles.length === 0) return;

    setAdding(true);
    try {
      const response = await fetch('/api/chapter-sources', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chapter_id: chapterId,
          file_ids: selectedFiles,
        }),
      });

      if (response.ok) {
        router.push(`/creator/book-compiler/${bookId}/chapters/${chapterId}`);
      } else {
        console.error('Failed to add sources');
      }
    } catch (err) {
      console.error('Error adding sources:', err);
    } finally {
      setAdding(false);
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-backend-secondary flex items-center justify-center">
        <div className="text-backend-primary text-lg">Loading Orb resonance suggestions...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-backend-secondary">
      <div className="max-w-6xl mx-auto px-6 py-12">
        <PageHeader
          title={`Orb-Resonance Sources for ${chapterTitle}`}
          subtitle="AI-powered content suggestions based on Orb associations and resonance"
          action={
            <div className="flex gap-3">
              <Button
                onClick={() => router.back()}
                variant="secondary"
              >
                ← Back to Chapter
              </Button>
              <Button
                onClick={handleAddSources}
                variant="primary"
                disabled={selectedFiles.length === 0 || adding}
              >
                {adding ? 'Adding...' : `Add ${selectedFiles.length} Sources`}
              </Button>
            </div>
          }
        />

        {suggestions.length === 0 ? (
          <EmptyState
            title="No Orb Resonance Found"
            description="No content files show meaningful Orb resonance with this chapter. Try adding more content or adjusting chapter metadata."
            action={
              <Button onClick={() => router.back()} variant="primary">
                Back to Chapter
              </Button>
            }
          />
        ) : (
          <div className="space-y-6">
            <div className="bg-backend-primary/5 rounded-lg p-6 border border-backend-primary/20">
              <h3 className="text-lg font-semibold text-backend-primary mb-2">
                Orb-Resonance Intelligence
              </h3>
              <p className="text-backend-secondary text-sm">
                These suggestions are generated by analyzing Orb associations, tag resonance, 
                and content type alignment between your chapter and the content library. 
                Higher resonance scores indicate stronger thematic and energetic connections.
              </p>
            </div>

            <div className="grid gap-4">
              {suggestions.map((suggestion, index) => (
                <Card key={suggestion.contentFile.id} className="relative">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <input
                          type="checkbox"
                          checked={selectedFiles.includes(suggestion.contentFile.id)}
                          onChange={() => toggleFileSelection(suggestion.contentFile.id)}
                          className="w-4 h-4 text-backend-primary"
                        />
                        <h3 className="text-lg font-semibold text-backend-primary">
                          {suggestion.contentFile.title}
                        </h3>
                        <div className="flex items-center gap-2">
                          <span className="px-2 py-1 bg-backend-primary/10 text-backend-primary text-xs rounded">
                            {Math.round(suggestion.resonanceScore * 100)}% Resonance
                          </span>
                          <span className="px-2 py-1 bg-backend-secondary/20 text-backend-secondary text-xs rounded">
                            {suggestion.contentFile.content_type}
                          </span>
                        </div>
                      </div>
                      
                      <p className="text-backend-secondary text-sm mb-3">
                        {suggestion.reasoning}
                      </p>
                      
                      <div className="flex flex-wrap gap-2 mb-3">
                        {suggestion.orbAlignment.slice(0, 5).map((alignment, idx) => (
                          <span
                            key={idx}
                            className="px-2 py-1 bg-backend-accent/20 text-backend-accent text-xs rounded"
                          >
                            {alignment}
                          </span>
                        ))}
                        {suggestion.orbAlignment.length > 5 && (
                          <span className="px-2 py-1 bg-backend-muted/20 text-backend-muted text-xs rounded">
                            +{suggestion.orbAlignment.length - 5} more
                          </span>
                        )}
                      </div>
                      
                      <div className="text-xs text-backend-muted">
                        {suggestion.contentFile.file_path} • {suggestion.contentFile.word_count || 0} words
                      </div>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}